# Generated by Django 3.1.3 on 2020-11-12 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='ATMachine',
            fields=[
                ('ATM_UID', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('minimum_balance', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('last_refill_date', models.DateField()),
                ('next_maintenance_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('pin', models.CharField(max_length=4)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('twoFA_status', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=11)),
                ('card_status', models.BooleanField(default=False)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.account')),
            ],
        ),
        migrations.CreateModel(
            name='PinChangeTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_transaction', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('response_code', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=100)),
                ('previous_pin', models.CharField(max_length=4)),
                ('new_pin', models.CharField(max_length=4)),
                ('ATM_UID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.atmachine')),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneChangeTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_transaction', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('response_code', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=100)),
                ('new_phone_number', models.CharField(max_length=11)),
                ('ATM_UID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.atmachine')),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashWithdrawalTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_transaction', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('response_code', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=100)),
                ('amount_transferred', models.PositiveIntegerField()),
                ('denomination', models.CharField(max_length=100)),
                ('current_balance', models.IntegerField()),
                ('ATM_UID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.atmachine')),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashTransferTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_transaction', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('response_code', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=100)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('amount_transferred', models.PositiveIntegerField()),
                ('ATM_UID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.atmachine')),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.account')),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceInquiryTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_transaction', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('response_code', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=100)),
                ('balance_amount', models.IntegerField()),
                ('ATM_UID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.atmachine')),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ATM_Refill',
            fields=[
                ('refill_ID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('atm_branch', models.CharField(max_length=100)),
                ('refill_date', models.DateField()),
                ('pervious_balance', models.PositiveIntegerField()),
                ('ATM_UID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.atmachine')),
            ],
        ),
    ]
