# Generated by Django 3.1.3 on 2020-11-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
