# Generated by Django 3.1.3 on 2020-11-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201113_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='account_number',
            new_name='account',
        ),
    ]
